### ISSUE TITLE
Formatter trying to convert lambda expression in Snakemake file causes error

### ISSUE THREAD

**Issue by dawnmy** [microsoft/vscode-anaconda-extension-pack#11]
- VSCode Version:1.35.1
- OS Version:MacOS 10.14.5 and Debian 3.16.43
- Anaconda Extension Pack Version: 1.0.1

Steps to Reproduce:

1. Install Python extension, Anaconda Extension Pack, pylint and autopep8, turn on Format on Save.
2. Create a Snakemake file with input containing lambda expression, for instance:
```python
rule proc_with_lambda:
    input:
        ref = lambda w: "ref1"
    output: "test.done"
    shell: "touch test.done"
```
3. Save this file, then you will see the lambda `ref` has been replaced with a standard function:
```python
def ref(w):
    return "ref1"
```
This will cause SyntaxError when executing the Snakemake workflow.

4. After I disable this extension, this conversion disappears.

Since Snakemake file is respected as Python file in VS code and the formatter works in the way for Python which causes the problem. It would be great to have Snakemake syntax support, and formatter independent from Python.

**Comment by brettcannon** [comment]
The Anaconda extension pack doesn't actually provide any of this functionality, so this isn't the right place to file a bug report. My guess is it's autopep8 that's rewriting the `lambda` function. I would try turning it off and see if that fixes the problem. If it does and you don't like that rewriting I would either see if you can turn it off or try another formatter like Black.
