### ISSUE TITLE
Extension does not seem to update python path/version for environment

### ISSUE THREAD

**Issue by SiavoshZarrasvand** [Microsoft/vscode-anaconda-extension-pack#4]
The extension does not create a virtual python environment properly. It ignores the Python version in the environment and uses the default "path" version of python. 

In the image below you can see that Visual Studio Code shows the python version as 3.6, while the command line shows it as 2.7. In both cases, the same environment is activated, and the proper version for the environment is 2.7.  

<img width="495" alt="screen shot 2018-07-14 at 12 23 22" src="https://user-images.githubusercontent.com/492510/42723969-6add1e9e-8761-11e8-854a-0935ef50d3ec.png">

**Comment by SiavoshZarrasvand** [comment]
A way to get by this at the moment is using the VS Code command palette and set the environment manually, then afterward use "source activate <environment>" from within the Visual Studio Code integrated bash window. 

That solved it for me for the time being. 
<img width="825" alt="screen shot 2018-07-14 at 13 11 08" src="https://user-images.githubusercontent.com/492510/42724286-52b960e2-8767-11e8-8058-37f350c52823.png">

**Comment by brettcannon** [comment]
This is controlled by microsoft/vscode-python and so that's the appropriate place to file a bug about this.

**Comment by SiavoshZarrasvand** [comment]
That can't be right, you must have misunderstood me. 

1. You start the plugin from within Anaconda Navigator for your active environment. If the idea of the Anaconda Navigator integration is to load a VS Code instance with the conda environment pre-loaded in the VS Code terminal, then shouldn't Anaconda Navigator be responsible for setting the paths as well? 

2. If that isn't the idea, what is the point of the Anaconda Navigator integration? As I wrote in my second comment, it was very easy for me to load VS Code and set the environment manually via the command palette, then activate the environment via the VS Code terminal. 

3. If you do not intend to actually set the paths, I suggest you remove the extension as I really don't think it is the VS Code Python plugin's duty to calculate how all others potential users and third party providers might be using their plugin. Frankly, I doubt it's even possible.

**Comment by brettcannon** [comment]
We actually don't handle the Anaconda Navigator integration. We simply provide an extension pack of extensions that Anaconda automatically installs on your behalf when you install VS Code (i.e. it's as if you downloaded VS Code manually and then installed this extension pack from the VS Code Marketplace, at least from our end). So if you are suggesting e.g. creating a default `settings.json` pointing `python.pythonPath` to your install of Python through Anaconda, then that sounds like a neat idea but that's a feature request for Anaconda Navigator itself.

**Comment by SiavoshZarrasvand** [comment]
@brettcannon Thanks a lot, that explains a few things. I'll see if I can progress both these streams 👍
